// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/generic.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DB_InserterClient is the client API for DB_Inserter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DB_InserterClient interface {
	Insert(ctx context.Context, in *ProtobufInsertRequest, opts ...grpc.CallOption) (*ProtobufInsertResponse, error)
}

type dB_InserterClient struct {
	cc grpc.ClientConnInterface
}

func NewDB_InserterClient(cc grpc.ClientConnInterface) DB_InserterClient {
	return &dB_InserterClient{cc}
}

func (c *dB_InserterClient) Insert(ctx context.Context, in *ProtobufInsertRequest, opts ...grpc.CallOption) (*ProtobufInsertResponse, error) {
	out := new(ProtobufInsertResponse)
	err := c.cc.Invoke(ctx, "/DB_Inserter/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DB_InserterServer is the server API for DB_Inserter service.
// All implementations must embed UnimplementedDB_InserterServer
// for forward compatibility
type DB_InserterServer interface {
	Insert(context.Context, *ProtobufInsertRequest) (*ProtobufInsertResponse, error)
	mustEmbedUnimplementedDB_InserterServer()
}

// UnimplementedDB_InserterServer must be embedded to have forward compatible implementations.
type UnimplementedDB_InserterServer struct {
}

func (UnimplementedDB_InserterServer) Insert(context.Context, *ProtobufInsertRequest) (*ProtobufInsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedDB_InserterServer) mustEmbedUnimplementedDB_InserterServer() {}

// UnsafeDB_InserterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DB_InserterServer will
// result in compilation errors.
type UnsafeDB_InserterServer interface {
	mustEmbedUnimplementedDB_InserterServer()
}

func RegisterDB_InserterServer(s grpc.ServiceRegistrar, srv DB_InserterServer) {
	s.RegisterService(&DB_Inserter_ServiceDesc, srv)
}

func _DB_Inserter_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtobufInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DB_InserterServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DB_Inserter/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DB_InserterServer).Insert(ctx, req.(*ProtobufInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DB_Inserter_ServiceDesc is the grpc.ServiceDesc for DB_Inserter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DB_Inserter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DB_Inserter",
	HandlerType: (*DB_InserterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _DB_Inserter_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/generic.proto",
}
