# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneric.proto\x1a\x19google/protobuf/any.proto\"T\n\x17protobuf_insert_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\'\n\tprotobufs\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"(\n\x18protobuf_insert_response\x12\x0c\n\x04\x65rrs\x18\x01 \x03(\t2L\n\x0b\x44\x42_Inserter\x12=\n\x06Insert\x12\x18.protobuf_insert_request\x1a\x19.protobuf_insert_responseB\x0bZ\t../commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t../common'
  _globals['_PROTOBUF_INSERT_REQUEST']._serialized_start=44
  _globals['_PROTOBUF_INSERT_REQUEST']._serialized_end=128
  _globals['_PROTOBUF_INSERT_RESPONSE']._serialized_start=130
  _globals['_PROTOBUF_INSERT_RESPONSE']._serialized_end=170
  _globals['_DB_INSERTER']._serialized_start=172
  _globals['_DB_INSERTER']._serialized_end=248
# @@protoc_insertion_point(module_scope)
