# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generic_pb2 as generic__pb2


class DB_InserterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/DB_Inserter/Insert',
                request_serializer=generic__pb2.protobuf_insert_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_insert_response.FromString,
                )


class DB_InserterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DB_InserterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=generic__pb2.protobuf_insert_request.FromString,
                    response_serializer=generic__pb2.protobuf_insert_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DB_Inserter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DB_Inserter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DB_Inserter/Insert',
            generic__pb2.protobuf_insert_request.SerializeToString,
            generic__pb2.protobuf_insert_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
